/** Full topic → skills catalogue for Coaching Development Table. */
export const TOPIC_SKILL_SPECS = [
  {
    id: "technical-ability",
    label: "Technical Ability",
    summary: "On-the-ball technique and execution.",
    skills: [
      "First Touch",
      "Ball Control",
      "Close Control",
      "Passing Accuracy",
      "Short Passing",
      "Long Passing",
      "Through Balls",
      "Crossing",
      "Finishing",
      "Long Shots",
      "Volleys",
      "Heading Accuracy",
      "Weak Foot Use",
      "Dribbling",
      "1v1 Ability",
      "Shielding Ball",
      "Chip Pass",
      "Driven Pass",
      "Curve on Ball",
      "Free Kick Technique",
    ],
  },
  {
    id: "tactical-intelligence",
    label: "Tactical Intelligence",
    summary: "Reading the game, space, and structure.",
    skills: [
      "Positioning",
      "Spatial Awareness",
      "Game Reading",
      "Decision Making",
      "Timing of Runs",
      "Defensive Shape Understanding",
      "Press Resistance",
      "Transition Awareness",
      "Offside Line Control",
      "Marking Intelligence",
      "Covering Space",
      "Tempo Control",
      "Counter Attack Recognition",
      "Line Breaking Vision",
      "Rotation Understanding",
      "Numerical Superiority Recognition",
      "Third Man Awareness",
      "Zone Occupation",
      "Compactness Understanding",
      "Tactical Discipline",
    ],
  },
  {
    id: "mental-attributes",
    label: "Mental Attributes",
    summary: "Mindset, character, and mental performance.",
    skills: [
      "Confidence",
      "Leadership",
      "Composure",
      "Concentration",
      "Competitive Mentality",
      "Resilience",
      "Patience",
      "Courage",
      "Accountability",
      "Discipline",
      "Motivation",
      "Work Ethic",
      "Winning Mentality",
      "Emotional Control",
      "Adaptability",
      "Self Belief",
      "Focus Under Pressure",
      "Consistency",
      "Responsibility",
      "Determination",
    ],
  },
  {
    id: "physical-attributes",
    label: "Physical Attributes",
    summary: "Speed, power, endurance, and movement quality.",
    skills: [
      "Pace",
      "Acceleration",
      "Sprint Speed",
      "Agility",
      "Balance",
      "Strength",
      "Power",
      "Stamina",
      "Endurance",
      "Jumping Reach",
      "Reaction Speed",
      "Coordination",
      "Mobility",
      "Flexibility",
      "Change of Direction",
      "Core Strength",
      "Explosiveness",
      "Recovery Speed",
      "Physical Duels",
      "Body Stability",
    ],
  },
  {
    id: "defensive-skills",
    label: "Defensive Skills",
    summary: "Stopping attacks and regaining the ball.",
    skills: [
      "Tackling",
      "Interceptions",
      "Blocking",
      "Defensive Positioning",
      "Pressing Intensity",
      "Delay Defender Skill",
      "Recovery Runs",
      "Aerial Duels",
      "1v1 Defending",
      "Channel Defending",
      "Screening Back Line",
      "Second Ball Winning",
      "Aggressive Defending",
      "Anticipation",
      "Clearances",
      "Tracking Runners",
      "Body Contact Use",
      "Compact Defending",
      "Defensive Communication",
      "Counter Pressing",
    ],
  },
  {
    id: "attacking-skills",
    label: "Attacking Skills",
    summary: "Creating and finishing chances.",
    skills: [
      "Movement Off Ball",
      "Creativity",
      "Final Pass",
      "Killer Instinct",
      "Combination Play",
      "Overlap Timing",
      "Underlap Timing",
      "Box Movement",
      "Near Post Runs",
      "Far Post Runs",
      "Hold Up Play",
      "Link Up Play",
      "Improvisation",
      "Finishing Under Pressure",
      "One Touch Finishing",
      "Counter Attack Speed",
      "Chance Creation",
      "Wide Isolation Ability",
      "Cut Inside Threat",
      "Penalty Taking",
    ],
  },
  {
    id: "midfielder-elite-habits",
    label: "Midfielder / Elite Habits (Fabregas Type)",
    summary: "Elite midfield habits: scanning, body shape, and progression.",
    skills: [
      "Scanning",
      "Shoulder Checks",
      "Pre-Scanning",
      "Open Body Shape",
      "Half Turn Receiving",
      "Looking Forward First",
      "Receive Between Lines",
      "One Touch Awareness",
      "Forward Passing Mindset",
      "Play Before Receiving",
      "Tempo Dictation",
      "Passing Rhythm",
      "Vision Before Ball Arrives",
      "Progressive Receiving",
      "Press Escape Awareness",
    ],
  },
  {
    id: "communication-leadership",
    label: "Communication / Leadership",
    summary: "Leading and organising on the pitch.",
    skills: [
      "Vocal Leadership",
      "Organising Teammates",
      "Trigger Communication",
      "Defensive Instructions",
      "Positive Energy",
      "Calmness to Team",
      "Accountability Standards",
      "Motivation of Teammates",
      "In-Game Corrections",
      "Captain Presence",
    ],
  },
  {
    id: "coach-evaluation-development",
    label: "Coach Evaluation / Development",
    summary: "How players respond to coaching and grow.",
    skills: [
      "Coachability",
      "Learning Speed",
      "Tactical Understanding",
      "Role Adaptation",
      "Training Intensity",
      "Consistency in Sessions",
      "Match Application",
      "Feedback Response",
      "Habit Building",
      "Growth Potential",
    ],
  },
  {
    id: "goalkeeper-specific",
    label: "Goalkeeper Specific",
    summary: "GK-specific actions and decision-making.",
    skills: [
      "Handling",
      "Shot Stopping",
      "Reflexes",
      "Positioning",
      "Distribution",
      "Sweeper Keeper Actions",
      "Aerial Claims",
      "Command of Area",
      "Penalty Saving",
      "Communication from Goal",
    ],
  },
  {
    id: "data-modern-football-metrics",
    label: "Data / Modern Football Metrics",
    summary: "Quantifiable performance indicators.",
    skills: [
      "Expected Threat Creation",
      "Progressive Passes",
      "Progressive Carries",
      "Duels Won %",
      "Press Success %",
      "Ball Recoveries",
      "Distance Covered",
      "High Intensity Runs",
      "Chances Created",
      "Possession Retention",
    ],
  },
  {
    id: "advanced-technical",
    label: "Advanced Technical",
    summary: "High-level execution and deception with the ball.",
    skills: [
      "Blind Side First Touch",
      "Touch Into Space",
      "One Touch Passing",
      "Two Footed Passing",
      "Bounce Pass Execution",
      "Outside Foot Pass",
      "Disguised Pass",
      "Reverse Pass",
      "No Look Pass",
      "Lofted Through Ball",
      "Cut Back Delivery",
      "Low Cross Accuracy",
      "Early Cross Timing",
      "Half Volley Strike",
      "Toe Poke Finish",
      "Near Post Finish",
      "Far Corner Finish",
      "First Time Cross",
      "Drag Back Control",
      "Turn Under Pressure",
    ],
  },
  {
    id: "advanced-tactical",
    label: "Advanced Tactical",
    summary: "Elite game structure, pressing, and manipulation.",
    skills: [
      "Blind Side Movement",
      "Occupying Half Spaces",
      "Between Line Positioning",
      "Rest Defence Awareness",
      "Trigger Press Recognition",
      "Press Trap Understanding",
      "Overload Creation",
      "Weak Side Exploitation",
      "Switch of Play Timing",
      "Width Management",
      "Depth Management",
      "Pinning Defenders",
      "Creating Passing Angles",
      "Double Movement Timing",
      "Decoy Runs",
      "Compactness Recovery",
      "Defensive Cover Shadow",
      "Counter Prevention",
      "Game State Management",
      "Match Momentum Reading",
    ],
  },
  {
    id: "advanced-mental",
    label: "Advanced Mental",
    summary: "Elite mindset under pressure and adversity.",
    skills: [
      "Ice Cold Finishing Mindset",
      "Bounce Back Ability",
      "Ruthlessness",
      "Sacrifice Mentality",
      "Hunger to Improve",
      "Big Match Personality",
      "Pressure Enjoyment",
      "Calm Under Chaos",
      "Attention to Detail",
      "Obsession With Winning",
      "Tactical Patience",
      "Controlled Aggression",
      "Competitive Edge",
      "Confidence After Mistakes",
      "Fearlessness",
    ],
  },
  {
    id: "advanced-physical",
    label: "Advanced Physical",
    summary: "Elite athletic traits and durability.",
    skills: [
      "Repeat Sprint Ability",
      "Top Speed Maintenance",
      "Contact Balance",
      "Landing Mechanics",
      "Hamstring Resilience",
      "Deceleration Strength",
      "Lateral Quickness",
      "Elasticity",
      "Explosive First Step",
      "Upper Body Power",
      "Lower Body Power",
      "Collision Strength",
      "Durability",
      "Recovery Capacity",
      "Work Rate Engine",
    ],
  },
  {
    id: "defensive-specialist",
    label: "Defensive Specialist",
    summary: "Advanced defending actions and duels.",
    skills: [
      "Last Man Defending",
      "Front Foot Defending",
      "Back Pedal Control",
      "Jockeying",
      "Tackling Timing",
      "Slide Tackle Precision",
      "Shoulder Duel Strength",
      "Box Defending",
      "Near Post Defending",
      "Far Post Defending",
      "Cross Prevention",
      "Emergency Defending",
      "2v1 Defending",
      "Delay Counter Attack",
      "Defensive Body Shape",
    ],
  },
  {
    id: "attacking-specialist",
    label: "Attacking Specialist",
    summary: "Advanced attacking movement and finishing.",
    skills: [
      "Separation Creation",
      "Explosive Run In Behind",
      "Curved Runs",
      "Double Movement in Box",
      "Timing to Attack Space",
      "Finishing From Cutbacks",
      "Poacher Instinct",
      "Rebound Awareness",
      "Chaos Finishing",
      "Hold Defender Off",
      "Turn and Shoot",
      "Layoff Quality",
      "Assist Vision",
      "Dribble to Final Third",
      "Final Third Decisions",
    ],
  },
  {
    id: "midfield-mastery",
    label: "Midfield Mastery",
    summary: "Controlling midfield rhythm and progression.",
    skills: [
      "Press Escape Turns",
      "Receiving on Back Foot",
      "Midfield Scanning Frequency",
      "Tempo Acceleration",
      "Tempo Slowing Control",
      "Dictating Possession",
      "Midfield Balance Awareness",
      "Support Angle Creation",
      "Recycling Possession",
      "Vertical Progression",
      "Third Man Release",
      "Rhythm Setting",
      "Deep Build Up Composure",
      "Passing Lane Manipulation",
      "Switch Tempo Intelligence",
    ],
  },
  {
    id: "wide-player-winger",
    label: "Wide Player / Winger",
    summary: "Wide attacking threat and combinations.",
    skills: [
      "Isolation Confidence",
      "Cross After Sprint",
      "Beat Fullback Outside",
      "Beat Fullback Inside",
      "Cutback Awareness",
      "Weak Foot Crossing",
      "1v2 Escape Ability",
      "Wide Combination Play",
      "Far Post Arrival",
      "Defensive Tracking Wide",
    ],
  },
  {
    id: "full-back-wing-back",
    label: "Full Back / Wing Back",
    summary: "Wide defensive and attacking contribution.",
    skills: [
      "Overlap End Product",
      "Recovery Sprinting",
      "Wide Defensive Timing",
      "Inverted Fullback IQ",
      "Underlap Runs",
      "Crossing on Move",
      "Wide Channel Defending",
      "Support Under Pressure",
      "Back Post Covering",
      "Endline Delivery",
    ],
  },
  {
    id: "centre-back",
    label: "Centre Back",
    summary: "Central defending and build-up.",
    skills: [
      "Build Up Passing",
      "Step Into Midfield",
      "Aerial Dominance",
      "Defensive Leadership",
      "Recovery Pace CB",
      "Duel Anticipation",
      "Body Position in Duels",
      "Line Control",
      "Front Foot Interceptions",
      "Ball Carrying From Back",
    ],
  },
  {
    id: "striker",
    label: "Striker",
    summary: "Leading the line and converting chances.",
    skills: [
      "Penalty Box Presence",
      "Shoulder to Goal Play",
      "Running Channels",
      "One Chance One Goal Mentality",
      "Separation in Box",
      "Header Timing",
      "Near Post Movement",
      "False Nine Link Play",
      "Pin Centre Backs",
      "Clinical Touches",
    ],
  },
  {
    id: "coach-development-metrics",
    label: "Coach Development Metrics",
    summary: "How you coach: sessions, detail, and leadership.",
    skills: [
      "Session Intensity",
      "Tactical Teaching Quality",
      "Detail Orientation",
      "Individual Development Focus",
      "Drill Communication",
      "In Game Adaptation",
      "Team Motivation Skill",
      "Match Preparation Quality",
      "Opposition Analysis Skill",
      "Leadership Presence as Coach",
    ],
  },
] as const;
