import type { Position } from "@/types";
import { primaryPositionFromList } from "@/lib/player-positions";

/**
 * Top 10 de qualidades (rótulos PT) por posição — base para a ficha «Observação» / jogador externo.
 * A posição principal numa lista multi-posição segue `primaryPositionFromList`.
 */
export const SKETCH_EXTERNAL_QUALITY_LABELS_BY_POSITION: Record<Position, readonly string[]> = {
  GK: [
    "Reflexos e estiradas",
    "Jogo de pés e saída curta",
    "Posicionamento entre postes",
    "Comunicação e liderança",
    "Saídas ao alto e cruzamentos",
    "Defesa de 1v1 e penáltis",
    "Distribuição longa e troca de jogo",
    "Concentração e consistência",
    "Agilidade lateral e segunda reação",
    "Segurança nas mãos e controlo de ressaltos",
  ],
  CB: [
    "Leitura defensiva e antecipação",
    "Duelos aéreos",
    "Um contra um frontal",
    "Passe progressivo e saída limpa",
    "Rapidez de reação nas costas",
    "Liderança e organização da linha",
    "Coberturas e apoios ao lateral",
    "Carga e agressividade controlada",
    "Resistência em duelos repetidos",
    "Capacidade física e impacto na área ofensiva",
  ],
  LB: [
    "Velocidade e profundidade",
    "Cruzamento e último passe na largura",
    "Um contra um defensivo",
    "Apoios, sobreposições e triângulos",
    "Intensidade e disciplina sem bola",
    "Passe vertical e ruptura",
    "Leitura do espaço entrelinhas",
    "Transições defesa-ataque",
    "Finalização ou remate de segunda linha",
    "Resistência e repetição de esforços",
  ],
  RB: [
    "Velocidade e profundidade",
    "Cruzamento e último passe na largura",
    "Um contra um defensivo",
    "Apoios, sobreposições e triângulos",
    "Intensidade e disciplina sem bola",
    "Passe vertical e ruptura",
    "Leitura do espaço entrelinhas",
    "Transições defesa-ataque",
    "Finalização ou remate de segunda linha",
    "Resistência e repetição de esforços",
  ],
  CDM: [
    "Leitura de jogo e posicionamento",
    "Interceções e cortes de linha",
    "Jogo de corpo e duelos no meio",
    "Passe sob pressão e ritmo",
    "Transições rápidas (recuperar e jogar à frente)",
    "Cargas ao portador e fechar espaços",
    "Coberturas ao médio ou lateral",
    "Proteção de bola sob pressing",
    "Remate de média distância",
    "Comunicação e comando do miolo",
  ],
  CM: [
    "Visão e último passe",
    "Ritmo, cadência e pausa",
    "Passe vertical e entrelinhas",
    "Proteção de bola e orientação",
    "Trabalho defensivo e pressing",
    "Apoios, triangulações e terceiro homem",
    "Finalização chegando à área",
    "Tomada de decisão sob pressão",
    "Resistência e volume de jogo",
    "Drible e saída no espaço curto",
  ],
  CAM: [
    "Criatividade e desequilíbrio",
    "Último passe e assistência",
    "Finalização e chegada à área",
    "Condução em progressão",
    "Orientação no último terço",
    "Leitura do desmarcar entre linhas",
    "Pressing alto e recuperações",
    "Remate de média distância",
    "Mobilidade e troca de corredor",
    "Capacidade física e repetição de sprints",
  ],
  LW: [
    "Velocidade",
    "Explosão / aceleração",
    "Drible no 1v1",
    "Tomada de decisão",
    "Cruzamento",
    "Finalização",
    "Inteligência tática",
    "Mudança de direção rápida",
    "Criatividade",
    "Capacidade física / resistência",
  ],
  RW: [
    "Velocidade",
    "Explosão / aceleração",
    "Drible no 1v1",
    "Tomada de decisão",
    "Cruzamento",
    "Finalização",
    "Inteligência tática",
    "Mudança de direção rápida",
    "Criatividade",
    "Capacidade física / resistência",
  ],
  ST: [
    "Finalização e frieza",
    "Movimento sem bola e desmarcar",
    "Jogo de costas e primeiro toque",
    "Profundidade e ruptura nas costas",
    "Duelos aéreos",
    "Força e proteção de bola",
    "Pressing ao primeiro defensor",
    "Associações curtas e paredes",
    "Impacto na pequena área",
    "Velocidade no último metro",
  ],
};

export function topSketchQualitiesForPositions(positions: Position[]): string[] {
  const primary = primaryPositionFromList(positions.length ? positions : ["CM"]);
  return [...SKETCH_EXTERNAL_QUALITY_LABELS_BY_POSITION[primary]];
}
